"""
Attack E1: Ornithopter Substitution
====================================
Tests classifier robustness against an adversarial drone whose body
RCS is drone-typical (rcs ~ 0.01 m^2) and whose bulk velocity falls in
the drone-typical range (5-20 m/s), but whose micro-Doppler signature
is generated by bird-style asymmetric flapping wings rather than by
rotating propellers. Models a flapping-wing UAV (ornithopter) or
mechanical bird.

Hypothesis (informed by FINDINGS_attribution):
  The classifier reads bulk-Doppler peak position+amplitude to identify
  drones; harmonic structure is ignored. An ornithopter with drone-
  typical body RCS and drone-typical bulk velocity preserves the
  bulk-Doppler peak in the drone-class region. The attribution
  prediction is therefore *null on drone classification*: drone-scale
  bulk peak should keep the prediction in the drone class even though
  the micro-Doppler is bird-like.

  This is the inverse of D1 (which moved bulk-Doppler into the bird
  band). E1 keeps bulk-Doppler in the drone band but replaces the
  propeller harmonic content with bird-flap content. If accuracy
  remains high, that confirms the attribution: the classifier does
  not read flap-vs-prop micro-Doppler structure.

  If accuracy *drops*, the classifier has additional dependence on
  micro-Doppler signature beyond what the attribution measured. Either
  outcome is informative.

Implementation:
  Custom signal generator combining drone bulk parameters with bird
  wing flap kinematics. No propeller blades; instead, asymmetric
  wing-flap modulation matching the bird-class generator.
"""

import numpy as np
import torch
import sys
import os
import json
sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'baseline'))

from fmcw_simulation import (compute_spectrogram, resize_spectrogram,
                              extract_bfp_features, generate_dataset, RadarParams)
from train_and_evaluate import train_cnn_lstm_model, create_sequences, CLASS_NAMES

SEED = int(os.environ.get('ATTACK_SEED', '42'))
N_ATTACK_SAMPLES = int(os.environ.get('ATTACK_N_SAMPLES', '150'))
np.random.seed(SEED)
torch.manual_seed(SEED)
print(f"(seed={SEED}, n_attack_samples={N_ATTACK_SAMPLES})")

DEVICE = 'cpu'
RESULTS_DIR = os.path.join(os.path.dirname(__file__), 'results')
os.makedirs(RESULTS_DIR, exist_ok=True)


def predict_sequences(model, X_seq, bfp_seq):
    model.eval()
    X_t = torch.FloatTensor(X_seq).unsqueeze(2).to(DEVICE)
    bfp_t = torch.FloatTensor(bfp_seq).to(DEVICE)
    preds = []
    batch = 16
    with torch.no_grad():
        for i in range(0, len(X_seq), batch):
            logits = model(X_t[i:i+batch], bfp_t[i:i+batch])
            preds.append(logits.argmax(dim=1).cpu().numpy())
    return np.concatenate(preds)


def build_clean_dataset_and_train():
    print("=" * 70)
    print("STEP 1: Generating clean 4-class dataset @ SNR=15dB")
    print("=" * 70)
    X, X_bfp, y = generate_dataset(n_samples_per_class=300, snr_db=15)

    n = len(y)
    n_tr, n_val = int(n * 0.70), int(n * 0.15)
    X_tr, X_val, X_te = X[:n_tr], X[n_tr:n_tr+n_val], X[n_tr+n_val:]
    bfp_tr, bfp_val, bfp_te = X_bfp[:n_tr], X_bfp[n_tr:n_tr+n_val], X_bfp[n_tr+n_val:]
    y_tr, y_val, y_te = y[:n_tr], y[n_tr:n_tr+n_val], y[n_tr+n_val:]

    Xs_tr, bfps_tr, ys_tr = create_sequences(X_tr, bfp_tr, y_tr, seq_len=10)
    Xs_val, bfps_val, ys_val = create_sequences(X_val, bfp_val, y_val, seq_len=10)
    Xs_te, bfps_te, ys_te = create_sequences(X_te, bfp_te, y_te, seq_len=10)

    print("Training CNN+LSTM+BFP baseline...")
    model, _ = train_cnn_lstm_model(
        Xs_tr, bfps_tr, ys_tr, Xs_val, bfps_val, ys_val, epochs=40)

    preds = predict_sequences(model, Xs_te, bfps_te)
    clean_acc = (preds == ys_te).mean()
    print(f"Clean-test accuracy: {clean_acc:.4f}")
    torch.save(model.state_dict(),
               os.path.join(RESULTS_DIR, 'cnn_lstm_bfp_baseline_e1.pt'))
    return model, float(clean_acc)


def generate_ornithopter_signal(R0, v_bulk, snr_db, params=RadarParams,
                                 flap_freq=8.0, wingspan=0.4,
                                 rcs_body_mean=0.01):
    """
    Drone-scale body RCS (~0.01) and drone-scale bulk velocity, but
    bird-style asymmetric flap micro-Doppler. Combines:
      - drone body amplitude (sqrt(rcs_body) * 1e3)
      - drone-class bulk Doppler position (passed v_bulk)
      - bird-style sinusoidal body oscillation (40% modulation)
      - bird-style wing-tip micro-Doppler with asymmetric downstroke
    """
    Nc, Ns = params.Nc, params.Ns
    rcs_body = rcs_body_mean + np.random.uniform(-0.005, 0.005)

    t_fast = np.arange(Ns) / params.fs
    t_slow = np.arange(Nc) * params.CRI

    R = R0 + v_bulk * t_slow
    tau = 2 * R / params.c
    f_beat = (params.B / params.Tc) * tau + 2 * v_bulk / params.lam
    phase_base = 4 * np.pi * R / params.lam
    phase = np.outer(f_beat, t_fast) * 2 * np.pi + phase_base[:, None]
    amplitude = np.sqrt(rcs_body) * 1e3

    # Body oscillation (bird-style: sinusoidal flap-driven amplitude
    # modulation of the body return)
    body_osc = 0.4 * np.sin(2 * np.pi * flap_freq * t_slow)
    beat_matrix = amplitude * (1 + body_osc[:, None]) * np.exp(1j * phase)

    # Wing micro-Doppler (bird-style: asymmetric downstroke 2x stronger)
    wing_phase_val = 2 * np.pi * flap_freq * t_slow
    v_wing = wingspan * 2 * np.pi * flap_freq * np.cos(wing_phase_val)
    asym = 1.0 + 1.0 * np.maximum(0, np.cos(wing_phase_val))
    f_md_wing = 2 * v_wing / params.lam
    md_amp = amplitude * 0.4 * asym
    md_phase = np.outer(f_md_wing, t_fast) * 2 * np.pi
    beat_matrix += md_amp[:, None] * np.exp(1j * (phase + md_phase))

    # Second-harmonic wing-tip return
    v_wing2 = wingspan * 0.7 * 2 * np.pi * flap_freq * np.cos(2 * wing_phase_val)
    f_md2 = 2 * v_wing2 / params.lam
    beat_matrix += (md_amp * 0.3)[:, None] * np.exp(1j * (phase + np.outer(f_md2, t_fast) * 2 * np.pi))

    sig_power = np.mean(np.abs(beat_matrix) ** 2)
    noise_power = sig_power / (10 ** (snr_db / 10))
    noise = np.sqrt(noise_power / 2) * (np.random.randn(Nc, Ns) + 1j * np.random.randn(Nc, Ns))
    return beat_matrix + noise


def generate_ornithopter_sample(flap_freq, wingspan, v_bulk_lo, v_bulk_hi,
                                 rcs_body_mean=0.01, snr_db=15):
    beat = generate_ornithopter_signal(
        R0=np.random.uniform(500, 2000),
        v_bulk=np.random.uniform(v_bulk_lo, v_bulk_hi),
        snr_db=snr_db,
        flap_freq=flap_freq,
        wingspan=wingspan,
        rcs_body_mean=rcs_body_mean,
    )
    spec, f, t = compute_spectrogram(beat)
    fs_stft = len(t) / (t[-1] - t[0]) if len(t) > 1 and t[-1] > t[0] else 1.0
    return resize_spectrogram(spec, (128, 128)), extract_bfp_features(spec, fs_stft)


def build_ornithopter_sequences(n_samples, flap_freq, wingspan,
                                 v_bulk_lo, v_bulk_hi, rcs_body_mean=0.01,
                                 seq_len=10):
    specs, bfps = [], []
    for _ in range(n_samples + seq_len - 1):
        # Sample flap_freq per frame from a window around the configured value
        ff = np.random.uniform(max(0.5, flap_freq - 2), flap_freq + 2)
        ws = np.random.uniform(max(0.1, wingspan - 0.1), wingspan + 0.1)
        s, b = generate_ornithopter_sample(ff, ws, v_bulk_lo, v_bulk_hi,
                                            rcs_body_mean=rcs_body_mean)
        specs.append(s)
        bfps.append(b)
    specs = np.array(specs, dtype=np.float32)
    bfps = np.array(bfps, dtype=np.float32)
    X_seq = np.array([specs[i:i+seq_len] for i in range(n_samples)])
    bfp_seq = np.array([bfps[i:i+seq_len] for i in range(n_samples)])
    return X_seq, bfp_seq


def run_attack(model, name, flap_freq, wingspan, v_lo, v_hi,
                rcs_body_mean, n_samples):
    X_seq, bfp_seq = build_ornithopter_sequences(
        n_samples, flap_freq, wingspan, v_lo, v_hi, rcs_body_mean)
    preds = predict_sequences(model, X_seq, bfp_seq)
    correct_as_drone = int((preds == 0).sum())
    accuracy = correct_as_drone / len(preds)
    class_distribution = {CLASS_NAMES[c]: int((preds == c).sum()) for c in range(4)}
    return {
        'attack_name': name,
        'flap_freq_hz': float(flap_freq),
        'wingspan_m': float(wingspan),
        'v_bulk_range_mps': [float(v_lo), float(v_hi)],
        'rcs_body_mean': float(rcs_body_mean),
        'n_samples': int(n_samples),
        'accuracy_as_drone': float(accuracy),
        'class_distribution': class_distribution,
    }


def main():
    model, clean_acc = build_clean_dataset_and_train()

    # Variants:
    #   - Standard ornithopter: drone RCS + drone speed + bird flap modulation
    #   - Bird-RCS variant: bird RCS body but drone speed (D1+E1 hybrid)
    #   - High flap-freq variant: tests if flap freq close to prop-typical region matters
    variants = [
        # (name,                flap_hz, wingspan, v_lo, v_hi, rcs_body_mean)
        ('E1_ornithopter_std',   8.0,    0.4,     5,    20,   0.01),
        ('E1_low_flap',          3.0,    0.5,     5,    20,   0.01),
        ('E1_high_flap',         15.0,   0.3,     5,    20,   0.01),
        ('E1_birdRCS_droneV',    8.0,    0.4,     5,    20,   0.005),
        ('E1_droneRCS_birdV',    8.0,    0.4,     5,    15,   0.01),
    ]

    print("\n" + "=" * 70)
    print("STEP 2: Running E1 ornithopter variants")
    print("=" * 70)

    results = {
        'baseline_clean_test_accuracy': clean_acc,
        'attacks': [],
    }

    for name, ff, ws, v_lo, v_hi, rcs in variants:
        print(f"\n  Running {name}: flap={ff}Hz, ws={ws}m, "
              f"v={v_lo}-{v_hi}m/s, rcs_body={rcs}")
        r = run_attack(model, name, ff, ws, v_lo, v_hi, rcs, N_ATTACK_SAMPLES)
        results['attacks'].append(r)
        print(f"    Accuracy (correct as drone): {r['accuracy_as_drone']:.3f}")
        print(f"    Class distribution: {r['class_distribution']}")

    out_path = os.path.join(RESULTS_DIR, 'attack_e1_results.json')
    with open(out_path, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to {out_path}")

    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"{'Variant':<28} {'Accuracy':<12} {'Dominant class':<25}")
    print("-" * 65)
    for r in results['attacks']:
        dominant = max(r['class_distribution'].items(), key=lambda x: x[1])
        print(f"{r['attack_name']:<28} "
              f"{r['accuracy_as_drone']:<12.3f} "
              f"{dominant[0]} ({dominant[1]})")


if __name__ == '__main__':
    main()
